# Generated by Django 2.2 on 2020-03-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200307_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('G', 'general')], max_length=1),
        ),
        migrations.AlterField(
            model_name='languages',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('G', 'general')], max_length=1),
        ),
        migrations.AlterField(
            model_name='novels',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('G', 'general')], max_length=1),
        ),
        migrations.AlterField(
            model_name='sciences',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('G', 'general')], max_length=1),
        ),
        migrations.AlterField(
            model_name='stationery',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('G', 'general')], max_length=1),
        ),
    ]
