# Generated by Django 2.2 on 2020-02-29 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNovels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Novels')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='novels',
            field=models.ManyToManyField(to='core.OrderNovels'),
        ),
    ]
