# Generated by Django 2.2 on 2020-03-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200309_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.IntegerField(default='')),
                ('email', models.EmailField(default='', max_length=254)),
                ('list_img', models.ImageField(default='', upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('checkout_request_id', models.CharField(default='', max_length=250)),
                ('transaction_initiated', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
