# Generated by Django 2.2 on 2020-03-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_booklists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklists',
            name='list_img',
            field=models.ImageField(upload_to='ListImages'),
        ),
    ]
