# Generated by Django 2.2 on 2020-03-09 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_bookshop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookLists',
            new_name='ItemList',
        ),
        migrations.CreateModel(
            name='ItemListsContents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=5)),
                ('quantity', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
                ('itemlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ItemList')),
            ],
        ),
    ]
