# Generated by Django 2.2 on 2020-03-09 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200309_1405'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemListsContents',
            new_name='ItemListContent',
        ),
    ]
